---
# configure deployment and continuous integration at travis-ci.com

arch: arm64
dist: jammy
language: java
os: linux

jobs:
  include:
    - script:
        - date
        - ./gradlew run --console=plain --stacktrace

addons:
  apt:
    update: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
