---
# GitHub Actions workflow for commits pushed to the jolt-jni repo - "master" branch

name: CI at GitHub
on:
  # trigger this workflow on pushes and also on pull requests
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Java11-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-13
    timeout-minutes: 9
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - run: ./gradlew run --console=plain

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-14
    timeout-minutes: 9
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v4
      - run: ./gradlew run --console=plain

  Java21-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    timeout-minutes: 9
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - run: ./gradlew run --console=plain
        shell: bash

  Java22-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    timeout-minutes: 9
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 22
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew run --console=plain
